name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Lint with black
      run: |
        black . --check --diff

    - name: Lint with flake8
      run: |
        flake8 . --statistics --count --show-source

    - name: Lint with isort
      run: |
        isort . --check-only --diff

    - name: Run unit tests
      run: |
        pytest --verbose --cov=sawatabi --cov-report=xml

    - name: Upload coverage reports to Codecov
      if: ${{ matrix.python-version == 3.8 }}
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
